cookai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("articles/", include("articles.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from users import views
from django.urls import path
app_name = 'users'

urlpatterns = [
    #회원가입
    path("signup/", views.UserSignupView.as_view(), name="signup"),

    #이메일인증
    path("activate/<slug:uidb64>/<slug:token>/", views.UserActivate.as_view(), name="activate"),
    path("success/", views.active_success, name="success"),

    #로그인
    path("login/", views.CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    #토큰 재발행
    path("login/refresh/", TokenRefreshView.as_view(), name="token_refresh"),

    # 로그아웃
    path("logout/", views.UserLogoutView.as_view(), name='logout'),

    # 마이페이지
    path('mypage/<int:user_id>/', views.MyPageView.as_view(), name="mypage"),
    path('mypage/<int:user_id>/', views.FollowView.as_view(), name="mypage"),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name="profile"),

    #팔로우
    path('follow/<int:user_id>/', views.FollowView.as_view(), name='follow_view'),

]

templates/email_active.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COOKAI</title>
</head>

<body>
    <h1>인증성공!</h1>
    <h1>회원가입이 완료되었습니다!</h1>
</body>

</html>

templates/email_signup_message.html
{{ user.username }}회원님 아래 링크를 눌러 인증해주세요.
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}